<?php

if(isset($_POST['submit'])){
// The user can just type in links from the url so the if statement above is checking if the user entered this page correctly from the form, the isset is checking if there are values in the form from which the submit button is coming from.......

// Now this is password reset functionality script

// Tokens auto generated by us are supposed to be cryptographically secured

$selector = bin2hex(random_bytes(8));
$token = random_bytes(32);
$url = "http://localhost/inmotionHubIct/createNewPassword.php?selector=" . $selector . "&validator=" . bin2hex($token);
$expires = date("U") + 1800;
require('Database/connection.php');

$userEmail = $_POST['email'];
$sql = "DELETE FROM pswdReset WHERE resetEmail=?";
$stmt = mysqli_stmt_init($con);
if(!mysqli_stmt_prepare($stmt, $sql)){
    echo "There was an error!!";
    exit();
}else{
    mysqli_stmt_bind_param($stmt, "s", $userEmail);
    mysqli_stmt_execute($stmt);
}
$sql = "INSERT INTO pswdReset (resetEmail, resetSelector, resetToken, resetExpires) VALUES (?, ?, ?, ?)";
$stmt = mysqli_stmt_init($con);
if(!mysqli_stmt_prepare($stmt, $sql)){
    echo "There was an error!!";
    exit();
}else{
    $hashedToken = password_hash($token, PASSWORD_DEFAULT);
    mysqli_stmt_bind_param($stmt, "ssss", $userEmail, $selector, $hashedToken, $expires);
    mysqli_stmt_execute($stmt);
}

mysqli_stmt_close($stmt);
mysqli_close($con);

$to = $userEmail;

$subject = "Reset Your Password for Inmotion-ict hub";
$message = '<p>We recieved a reset password. The link below can be used to make that request. You can ignore this email</p>';
$message .= '</p>Here is your reset password link.</br>';
$message .= '<a href="' . $url . '">' . $url . '</a></p>';
$headers = "from: Inmotion-ict hub <hello@inmotionhub.com\r\n>";
$headers .= "Reply-to: hello@inmotionhub.com\r\n";
$headers .= "Content-type: text/html\r\n";

mail($to, $subject, $message, $headers);

header("Location: reset-password.php?reset=success");

}else{
    header('Location: ../index.php');
}