<?php
// About Teacher fo teacher
if($_SESSION["name"][0] == "a" || $_SESSION["name"][0] == "A"){
$aboutTeacher = "<p>Hello, I'm " . $_SESSION["name"] .", proud to be part of " . $_SESSION["department"] ." With " . $_SESSION["experience"] ." of teaching experience, I guide students in " . $_SESSION["programming_language"] ." Fluent in " . $_SESSION["spoken_language"] . " language" ." I'm committed to fostering an engaging and supportive learning environment. Let's embark on this educational journey together, where passion meets proficiency, and every line of code counts.</p>";
}elseif($_SESSION["name"][0] == "b" || $_SESSION["name"][0] == "B"){
$aboutTeacher = "<p>Greetings, I am " . $_SESSION["name"] .", honored to contribute to " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." nurturing minds, I lead in " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", I am dedicated to cultivating an interactive and supportive learning atmosphere. Join me on this educational voyage, where enthusiasm merges seamlessly with expertise, and each line of code holds significance.</p>";
}elseif($_SESSION["name"][0] == "c" || $_SESSION["name"][0] == "C"){
$aboutTeacher = "<p>Celebrate with me as I join the " . $_SESSION["department"] ." team. With " . $_SESSION["experience"] ." nurturing minds, I specialize in " . $_SESSION["programming_language"] .". Fluent in " . $_SESSION["spoken_language"] . ", I'm dedicated to fostering a vibrant, supportive learning atmosphere. Join me on this educational adventure, where passion and skill unite, shaping every line of code.</p>";
}elseif($_SESSION["name"][0] == "d" || $_SESSION["name"][0] == "D"){
$aboutTeacher = "<p>Greetings, I'm " . $_SESSION["name"] .", delighted to contribute to " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of teaching, I lead students in " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my commitment lies in creating an immersive and supportive learning atmosphere. Join me on this educational voyage, where passion intertwines with proficiency, and every code line holds significance.</p>";
}elseif($_SESSION["name"][0] == "e" || $_SESSION["name"][0] == "E"){
$aboutTeacher = "<p>Greetings, I am " . $_SESSION["name"] .", honored to contribute to " . $_SESSION["department"] .". Bringing " . $_SESSION["experience"] ." of teaching expertise, I mentor students in " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my dedication is to cultivate an interactive and supportive learning atmosphere. Join me on this educational expedition, where the fusion of passion and proficiency elevates every line of code.</p>";
}elseif($_SESSION["name"][0] == "f" || $_SESSION["name"][0] == "F"){
$aboutTeacher = "<p>Greetings, I'm " . $_SESSION["name"] .", delighted to contribute to " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." instructing, I lead students in " . $_SESSION["programming_language"] .". Fluent in " . $_SESSION["spoken_language"] . ", I'm dedicated to cultivating an interactive and supportive learning atmosphere. Join me on this educational journey, where passion intersects with proficiency, and each code line holds significance.</p>";
}elseif($_SESSION["name"][0] == "g" || $_SESSION["name"][0] == "G"){
$aboutTeacher = "<p>Greetings, I am " . $_SESSION["name"] .", delighted to contribute to " . $_SESSION["department"] .". Leveraging " . $_SESSION["experience"] ." of teaching expertise, I mentor students in " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my dedication lies in cultivating an interactive and supportive learning atmosphere. Join me on this educational voyage, where the intersection of passion and proficiency elevates the significance of every line of code.</p>";
}elseif($_SESSION["name"][0] == "h" || $_SESSION["name"][0] == "H"){
$aboutTeacher = "<p>Hello, I'm " . $_SESSION["name"] .", and I take pride in being a part of " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of teaching experience, my focus lies in guiding students through the intricacies of " . $_SESSION["programming_language"] .". Fluent in " . $_SESSION["spoken_language"] . ", my commitment is to create an immersive and supportive learning environment. Let's embark on this educational journey together, seamlessly blending passion with proficiency, where every line of code carries significance.</p>";
}elseif($_SESSION["name"][0] == "i" || $_SESSION["name"][0] == "I"){
$aboutTeacher = "<p>Greetings, I'm " . $_SESSION["name"] .", honored to be part of the " . $_SESSION["department"] ." team. With " . $_SESSION["experience"] ." of teaching prowess, I specialize in guiding students through " . $_SESSION["programming_language"] .". Fluent in " . $_SESSION["spoken_language"] . ", I'm dedicated to fostering an immersive and supportive learning environment. Join me on this educational journey, where passion intertwines with expertise, and each code line is significant.</p>";
}elseif($_SESSION["name"][0] == "j" || $_SESSION["name"][0] == "J"){
$aboutTeacher = "<p>Hello, I'm " . $_SESSION["name"] .", thrilled to contribute to the " . $_SESSION["department"] ." community. Drawing on " . $_SESSION["experience"] ." of teaching experience, I specialize in guiding students through the intricacies of " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my commitment lies in cultivating a dynamic and supportive learning space. Join me on this educational adventure, where passion converges with expertise, and every line of code carries weight.</p>";
}elseif($_SESSION["name"][0] == "k" || $_SESSION["name"][0] == "K"){
$aboutTeacher = "<p>Hello, I'm " . $_SESSION["name"] .", privileged to join the esteemed " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of teaching experience, I excel in instructing students in " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my focus is on creating an engaging and supportive learning environment. Let's embark together on this educational journey, where passion and expertise converge, and every code line holds its significance.</p>";
}elseif($_SESSION["name"][0] == "l" || $_SESSION["name"][0] == "L"){
$aboutTeacher = "<p>Greetings, I am " . $_SESSION["name"] .", thrilled to be part of the distinguished " . $_SESSION["department"] .". Armed with " . $_SESSION["experience"] ." of teaching mastery, I specialize in guiding students through the intricacies of " . $_SESSION["programming_language"] .". Fluent in " . $_SESSION["spoken_language"] . ", my commitment lies in cultivating a dynamic and supportive learning ambiance. Join me on this educational odyssey, where the fusion of passion and expertise accentuates the significance of every line of code.</p>";
}elseif($_SESSION["name"][0] == "m" || $_SESSION["name"][0] == "M"){
$aboutTeacher = "<p>Hello, I'm " . $_SESSION["name"] .", excited to contribute to the esteemed " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of teaching expertise, I specialize in mentoring students in " . $_SESSION["programming_language"] .". Fluent in " . $_SESSION["spoken_language"] . ", I'm dedicated to creating a dynamic and supportive learning environment. Join me on this educational journey, where the convergence of passion and proficiency amplifies the impact of every line of code.</p>";
}elseif($_SESSION["name"][0] == "n" || $_SESSION["name"][0] == "N"){
$aboutTeacher = "<p>Hello, I'm " . $_SESSION["name"] .", honored to contribute to the esteemed " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of teaching experience, I specialize in guiding students through " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", I'm committed to fostering a vibrant and supportive learning environment. Join me on this educational journey, where the synergy of passion and expertise illuminates the significance of each code line.</p>";
}elseif($_SESSION["name"][0] == "o" || $_SESSION["name"][0] == "O"){
$aboutTeacher = "<p>Hello, I'm " . $_SESSION["name"] .", excited to contribute to the esteemed " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of teaching experience, I specialize in instructing students in " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my dedication is to foster an interactive and supportive learning environment. Join me on this educational journey, where the blend of passion and expertise highlights the significance of each code line.</p>";
}elseif($_SESSION["name"][0] == "p" || $_SESSION["name"][0] == "P"){
$aboutTeacher = "<p>Greetings, I am " . $_SESSION["name"] .", honored to be a part of the esteemed " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of pedagogical expertise, I specialize in guiding students through the intricacies of " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my commitment lies in cultivating a dynamic and supportive learning ambiance. Join me on this educational odyssey, where the fusion of passion and expertise accentuates the significance of every line of code.</p>";
}elseif($_SESSION["name"][0] == "q" || $_SESSION["name"][0] == "Q"){
$aboutTeacher = "<p>Greetings, I am " . $_SESSION["name"] .", honored to be part of the esteemed " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of pedagogical expertise, I specialize in assisting students in navigating the intricacies of " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my commitment is to cultivate a dynamic and supportive learning atmosphere. Come join me on this educational adventure, where the blend of passion and expertise underscores the significance of each line of code.</p>";
}elseif($_SESSION["name"][0] == "r" || $_SESSION["name"][0] == "R"){
$aboutTeacher = "<p>Greetings, I am " . $_SESSION["name"] .", and it is an honor to be a part of the esteemed " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of pedagogical expertise, my specialization lies in guiding students through the intricacies of " . $_SESSION["programming_language"] .". Fluent in " . $_SESSION["spoken_language"] . ", my commitment is to foster a dynamic and supportive learning environment. I invite you to join me on this educational journey, where the fusion of passion and expertise emphasizes the significance of each line of code.</p>";
}elseif($_SESSION["name"][0] == "s" || $_SESSION["name"][0] == "S"){
$aboutTeacher = "<p>Hey there, I am " . $_SESSION["name"] .", and it is both a privilege and a pleasure to be associated with the esteemed " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of dedicated teaching experience, my expertise lies in guiding students through the intricacies of " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my focus is on creating a dynamic and supportive learning environment. I extend an invitation to you to join me on this educational journey, where the combination of passion and expertise underscores the profound importance of every line of code.</p>";
}elseif($_SESSION["name"][0] == "t" || $_SESSION["name"][0] == "T"){
$aboutTeacher = "<p>Hello, I am " . $_SESSION["name"] .", delighted to contribute to the prestigious " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of teaching experience, my focus is on assisting students in navigating the complexities of " . $_SESSION["programming_language"] .". Fluent in " . $_SESSION["spoken_language"] . ", I am dedicated to cultivating an engaging and supportive learning environment. Join me in this educational adventure, where the blend of passion and expertise highlights the importance of each line of code.</p>";
}elseif($_SESSION["name"][0] == "u" || $_SESSION["name"][0] == "U"){
$aboutTeacher = "<p>Greetings, I am " . $_SESSION["name"] .", privileged to be a member of the esteemed " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of pedagogical expertise, I specialize in guiding students through the intricacies of " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my commitment lies in creating a dynamic and supportive learning atmosphere. I invite you to embark on this educational journey with me, where the fusion of passion and expertise underscores the significance of every line of code.</p>";
}elseif($_SESSION["name"][0] == "v" || $_SESSION["name"][0] == "V"){
$aboutTeacher = "<p>Warm greetings! I'm " . $_SESSION["name"] .", thrilled to contribute to the esteemed " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of teaching expertise, I excel in guiding students through the nuances of " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my commitment lies in fostering a collaborative and supportive learning environment. I extend an invitation to you to embark on this educational expedition, where the convergence of passion and proficiency celebrates the art of coding.</p>";
}elseif($_SESSION["name"][0] == "w" || $_SESSION["name"][0] == "W"){
$aboutTeacher = "<p>Hello, I am " . $_SESSION["name"] .", honored to contribute to the renowned " . $_SESSION["department"] .". Leveraging " . $_SESSION["experience"] ." of pedagogical insight, my forte is assisting students in navigating the intricacies of " . $_SESSION["programming_language"] .". Proficient in " . $_SESSION["spoken_language"] . ", my dedication centers on fostering a dynamic and supportive learning environment. I invite you to be a part of this educational voyage, where the confluence of passion and expertise emphasizes the profound importance of each line of code.</p>";
}elseif($_SESSION["name"][0] == "x" || $_SESSION["name"][0] == "X"){
$aboutTeacher = "<p>Greetings, I am " . $_SESSION["name"] .", thrilled to be a part of the esteemed " . $_SESSION["department"] .". With " . $_SESSION["experience"] ." of dedicated teaching, I specialize in guiding students through the complexities of " . $_SESSION["programming_language"] .". Fluent in " . $_SESSION["spoken_language"] . ", my commitment revolves around cultivating a dynamic and supportive learning atmosphere. I warmly welcome you to embark on this educational journey with me, where the fusion of passion and expertise illuminates the significance of each line of code.</p>";
}elseif($_SESSION["name"][0] == "y" || $_SESSION["name"][0] == "Y"){
$aboutTeacher = "<p>Greetings, I am " . $_SESSION["name"] .", and it is with great pride that I contribute to the esteemed Computer Science department. With a wealth of " . $_SESSION["experience"] ." in teaching, I specialize in guiding students through the intricacies of " . $_SESSION["programming_language"] .". My proficiency in " . $_SESSION["spoken_language"] . " allows me to create a vibrant and supportive learning environment. I welcome you to join me on this educational voyage, where the synergy of passion and expertise illuminates the significance of every line of code.</p>";
}else{
$aboutTeacher = "<p>Hello, I am ". $_SESSION["name"] .", and I am thrilled to be a part of the distinguished Software Engineering department. Drawing on " . $_SESSION["experience"] ." of teaching experience, I excel in navigating students through the complexities of " . $_SESSION["programming_language"] .". Fluent in " . $_SESSION["spoken_language"] . ", I am dedicated to cultivating an interactive and supportive learning atmosphere. I invite you to be part of this educational expedition, where the harmonious blend of passion and expertise underscores the profound importance of each code snippet.</p>";
}



// Qualification remarks
    if($_SESSION["spoken_language"] == "English"){
        $qualified = "<p>Welcome to the Qualifications section, where our esteemed instructors showcase their expertise. Meet " . $_SESSION["name"] .", an accomplished professional in the " . $_SESSION["department"] ." department. Fluent in " . $_SESSION["spoken_language"] . ", " . $_SESSION["name"] ." brings " . $_SESSION["experience"] ." of teaching mastery. The most proficient programming language is " . $_SESSION["programming_language"] .", reflecting a commitment to excellence. Elevate your learning journey with " . $_SESSION["name"] .".</p>";
    }elseif($_SESSION["spoken_language"] == "Mandarin Chinese"){
        $qualified = "<p>Welcome to the Qualifications section, where our esteemed instructors proudly exhibit their expertise. Allow me to introduce " . $_SESSION["name"] .", a distinguished professional in the " . $_SESSION["department"] ." department. Proficient in " . $_SESSION["spoken_language"] . ", " . $_SESSION["name"] ." brings a wealth of " . $_SESSION["experience"] ." of teaching mastery. The primary programming language is " . $_SESSION["programming_language"] .", underscoring a steadfast commitment to excellence. Enrich your educational journey by learning from the wealth of knowledge and experience that " . $_SESSION["name"] ." brings to the table.</p>";
    }elseif($_SESSION["spoken_language"] == "Spanish"){
        $qualified = "<p>Welcome to our Qualifications section, a space where our distinguished instructors present their expertise. Allow me to introduce you to " . $_SESSION["name"] .", a seasoned professional in the " . $_SESSION["department"] ." department. Proficient in " . $_SESSION["spoken_language"] . ", they bring " . $_SESSION["experience"] ." of mastery in the art of teaching. Their primary programming language proficiency lies in " . $_SESSION["programming_language"] .", exemplifying an unwavering commitment to excellence. Elevate your educational journey with the seasoned guidance of " . $_SESSION["name"] .".</p>";
    }else{
        $qualified = "<p>Step into our Qualifications section, where our esteemed instructors spotlight their expertise. Allow me to introduce " . $_SESSION["name"] .", an accomplished professional within our " . $_SESSION["department"] ." department. Proficient in " . $_SESSION["spoken_language"] . ", they bring " . $_SESSION["experience"] ." of teaching mastery. Their most proficient programming language is " . $_SESSION["programming_language"] .", showcasing a dedication to excellence. Enhance your learning journey with the guidance of " . $_SESSION["name"] .".</p>";
    }